services:
  webapi:
    image: ${PROJECT_NAME}/webapi
    build:
      context: WebApi
    ports:
      - 0.0.0.0:0:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/root
    depends_on:
      - sqlserver
    networks:
      - servernetwork
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 0:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MiH)|sn@9s>zAYs9
    networks:
      - servernetwork
  gameserver:
    image: ${PROJECT_NAME}/gameserver
    build:
      context: Server
    ports:
      - 0.0.0.0:0:7777
      - 0.0.0.0:0:7778
    networks:
      - servernetwork
      
networks:
    servernetwork:
        name: ${NETWORK}
        driver: bridge